# Generated by Django 4.2.6 on 2023-11-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeats',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('sl_no', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('departure_timings', models.CharField(max_length=50)),
                ('selected_seats', models.CharField(max_length=250)),
            ],
        ),
    ]
