# Generated by Django 4.2.6 on 2023-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_bookedseats_passenger_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseats',
            name='ticket_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
