# Generated by Django 4.2.6 on 2023-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0003_bookedseats_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedseats',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
