# Generated by Django 4.2.6 on 2023-11-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoutes',
            fields=[
                ('sl_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('depot', models.CharField(max_length=50)),
                ('route_no', models.CharField(max_length=10)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('route_length', models.CharField(max_length=10)),
                ('bus_type', models.CharField(max_length=50)),
                ('no_of_service', models.CharField(max_length=50)),
                ('departure_timings', models.CharField(max_length=50)),
            ],
        ),
    ]
